id: http://automate.website/draft-0.2/base-schema#
$schema: http://json-schema.org/draft-04/schema#
title: Web Automation Markup Language
description: A simple markup language for web automation.
type: array
items:
    $ref: http://automate.website/draft-0.2/scenario-schema#
additionalProperties: false