id: http://waml.automate.website/draft-0.2/base-command-schema#
$schema: http://json-schema.org/draft-04/schema#
properties:
    $schema:
        type: string
    if:
        oneOf:
            - $ref: http://waml.automate.website/draft-0.2/expression-schema#
            - type: boolean
        description: If set, the step is only executed if the value evaluates to true
    unless:
        oneOf:
            - $ref: http://waml.automate.website/draft-0.2/expression-schema#
            - type: boolean
        description: If set, the step is only executed if the value evaluates to false
